#Setup consists out of multiple devices:
#ESP Board: Node MCU V3
#MODBUS Board: MAX485 TTL to RS485 (HW-97)
#Inputs Board: N4DIH32 - 32Channel RS485 PNP Input

esphome:
  name: "ESP-N4DIH32"
  friendly_name: "ESP-N4DIH32"

esp8266:
  board: nodemcuv2

# disable logging
logger:
    baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  id: mod_bus_uart
  tx_pin: GPIO15
  rx_pin: GPIO13
  baud_rate: 9600
  parity: NONE 
  stop_bits: 1
  data_bits: 8

modbus:
  flow_control_pin: GPIO14
  id: mod_bus
  uart_id: mod_bus_uart

modbus_controller:
  - id: N4DIH32_Controller
    address: 0x03 #Modbus device address => DIP-Switches [1][1][0][0][0][0] = 0x03
    modbus_id: mod_bus
    setup_priority: -10
    update_interval: 1.0s

binary_sensor:

     #0x00C0 register (16bit) (X00-X15)
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X00
    register_type: holding
    address: 0x00C0
    bitmask: 0x1
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X01
    register_type: holding
    address: 0x00C0
    bitmask: 0x2
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X02
    register_type: holding
    address: 0x00C0
    bitmask: 0x4
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X03
    register_type: holding
    address: 0x00C0
    bitmask: 0x8
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X04
    register_type: holding
    address: 0x00C0
    bitmask: 0x10
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X05
    register_type: holding
    address: 0x00C0
    bitmask: 0x20
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X06
    register_type: holding
    address: 0x00C0
    bitmask: 0x40
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X07
    register_type: holding
    address: 0x00C0
    bitmask: 0x80
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X08
    register_type: holding
    address: 0x00C0
    bitmask: 0x100
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X09
    register_type: holding
    address: 0x00C0
    bitmask: 0x200
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X10
    register_type: holding
    address: 0x00C0
    bitmask: 0x400
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X11
    register_type: holding
    address: 0x00C0
    bitmask: 0x800
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X12
    register_type: holding
    address: 0x00C0
    bitmask: 0x1000
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X13
    register_type: holding
    address: 0x00C0
    bitmask: 0x2000
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X14
    register_type: holding
    address: 0x00C0
    bitmask: 0x4000
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X15
    register_type: holding
    address: 0x00C0
    bitmask: 0x8000

    #0x00C1 register  (16bit) (X16-X31)
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X16
    register_type: holding
    address: 0x00C1
    bitmask: 0x1
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X17
    register_type: holding
    address: 0x00C1
    bitmask: 0x2
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X18
    register_type: holding
    address: 0x00C1
    bitmask: 0x4
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X19
    register_type: holding
    address: 0x00C1
    bitmask: 0x8
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X20
    register_type: holding
    address: 0x00C1
    bitmask: 0x10
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X21
    register_type: holding
    address: 0x00C1
    bitmask: 0x20
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X22
    register_type: holding
    address: 0x00C1
    bitmask: 0x40
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X23
    register_type: holding
    address: 0x00C1
    bitmask: 0x80
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X24
    register_type: holding
    address: 0x00C1
    bitmask: 0x100
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X25
    register_type: holding
    address: 0x00C1
    bitmask: 0x200
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X26
    register_type: holding
    address: 0x00C1
    bitmask: 0x400
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X27
    register_type: holding
    address: 0x00C1
    bitmask: 0x800
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X28
    register_type: holding
    address: 0x00C1
    bitmask: 0x1000
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X29
    register_type: holding
    address: 0x00C1
    bitmask: 0x2000
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X30
    register_type: holding
    address: 0x00C1
    bitmask: 0x4000
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: Input X31
    register_type: holding
    address: 0x00C1
    bitmask: 0x8000


#diagnostics 
text_sensor:
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: "Baud Rate"
    entity_category: diagnostic
    register_type: holding
    address: 0x00FF
    raw_encode: HEXBYTES
    lambda: |-
      uint16_t value = modbus_controller::word_from_hex_str(x, 0);
      switch (value) 
      {
        case 0: return std::string("1200");
        case 1: return std::string("2400");
        case 2: return std::string("4800");
        case 3: return std::string("9600");
        case 4: return std::string("19200");
        default: return std::string("Unknown");
      }

number:
  - platform: modbus_controller
    modbus_controller_id: N4DIH32_Controller
    name: "Automatic Update Time"
    entity_category: diagnostic
    register_type: holding
    address: 0x00FD
    value_type: U_WORD
    unit_of_measurement: "s"

